#!/usr/bin/sh

# This hook uses a local clone of this repository to test the new commit before pushing.
# If it fails any tests or contains compiler errors, the commit will not be pushed.
# Note that only the latest commit will be tested.
#
# In order to use it:
# 1. Create a clone of this repository named 'mellow_bridge' next to the main project
# 2. Copy or create a symbolic link from `tests/git-hooks` to `.git/hooks`
#
# WARNING: With this setup, the `mellow_bridge` clone should be treated as read-only, as
# any changes made to it will be lost each time this hook runs. It merely serves as a
# as a local sandbox (or mirror) to test new commits before pushing them to GitHub.

mellow=$(git rev-parse --show-toplevel)
mellow_bridge="$mellow/../mellow_bridge"

if [ "$mellow" = "$mellow_bridge" ]; then
	cargo test && exit 0 || exit 1
fi

cd "$mellow_bridge" && git reset --hard origin/main && git pull "$mellow" && cargo test || {
	cd - \
  && echo "Please fix any errors introduced by the commit, then try again." \
	&& exit 1
}

cd - && exit 0
