#!/usr/bin/sh

# This hook uses a local clone of this repository to test the new commit before pushing.
# If it fails any tests or contains compiler errors, the commit will not be pushed.
#
# A local clone named `mellow_bridge` will be created next to this source directory when
# first running this hook, where latest commit will be tested. Note that `mellow_bridge`
# will not be connected to Github.
#
# In order to use it:
# Copy or create a symbolic link from `tests/git-hooks` to `.git/hooks`.
#
# WARNING: With this setup, the `mellow_bridge` clone should be treated as read-only, as
# any changes made to it will be lost each time this hook runs. It merely serves as a
# as a local sandbox (or mirror) to test new commits before pushing them to GitHub.
# WARNING: This hook should not be enabled in the `mellow_bridge` clone

mellow=$(git rev-parse --show-toplevel)
mellow_bridge="$mellow/../mellow_bridge"

echo "Updating $(realpath "$mellow_bridge"):"
cd "$mellow_bridge" && git pull --rebase --force || {
	git clone "$mellow" "$mellow_bridge" && cd "$mellow_bridge"
}

echo

cargo test || {
	  echo && cd - \
	  && echo "Please fix any errors introduced by the commit, then try again." \
		&& exit 1
}

echo

cd - && exit 0
